export const mockProducts = [
  {
    id: 1,
    name: "Cashmere Overcoat",
    category: "Outerwear",
    price: 1200,
    discount: 10,
    stock: 15,
    status: "In Stock",
    description: "Premium cashmere overcoat",
    images: ["/cashmere-overcoat-1.jpg", "/cashmere-overcoat-2.jpg"],
  },
  {
    id: 2,
    name: "Merino Wool Sweater",
    category: "Knitwear",
    price: 350,
    discount: 0,
    stock: 8,
    status: "Low Stock",
    description: "Fine merino wool sweater",
    images: ["/merino-sweater-1.jpg", "/merino-sweater-2.jpg"],
  },
  {
    id: 3,
    name: "Tailored Trousers",
    category: "Trousers",
    price: 280,
    discount: 15,
    stock: 22,
    status: "In Stock",
    description: "Perfectly tailored trousers",
    images: ["/tailored-trousers-1.jpg", "/tailored-trousers-2.jpg"],
  },
  {
    id: 4,
    name: "Oxford Shirt",
    category: "Shirts",
    price: 180,
    discount: 5,
    stock: 0,
    status: "Out of Stock",
    description: "Classic oxford shirt",
    images: ["/oxford-shirt-1.jpg", "/oxford-shirt-2.jpg"],
  },
  {
    id: 5,
    name: "Leather Loafers",
    category: "Footwear",
    price: 420,
    discount: 20,
    stock: 12,
    status: "In Stock",
    description: "Premium leather loafers",
    images: ["/leather-loafers-1.jpg", "/leather-loafers-2.jpg"],
  },
  {
    id: 6,
    name: "Silk Tie Collection",
    category: "Accessories",
    price: 95,
    discount: 0,
    stock: 45,
    status: "In Stock",
    description: "Luxury silk ties",
    images: ["/silk-tie-1.jpg", "/silk-tie-2.jpg"],
  },
  {
    id: 7,
    name: "Wool Blazer",
    category: "Outerwear",
    price: 850,
    discount: 12,
    stock: 6,
    status: "Low Stock",
    description: "Fine wool blazer",
    images: ["/wool-blazer-1.jpg", "/wool-blazer-2.jpg"],
  },
  {
    id: 8,
    name: "Cotton Socks Pack",
    category: "Accessories",
    price: 45,
    discount: 0,
    stock: 120,
    status: "In Stock",
    description: "Premium cotton socks",
    images: ["/cotton-socks-1.jpg", "/cotton-socks-2.jpg"],
  },
]

export const mockCategories = [
  { id: 1, name: "Outerwear", image: "/outerwear-category.jpg", productCount: 12, status: "Active" },
  { id: 2, name: "Knitwear", image: "/knitwear-category.jpg", productCount: 8, status: "Active" },
  { id: 3, name: "Trousers", image: "/trousers-category.jpg", productCount: 15, status: "Active" },
  { id: 4, name: "Shirts", image: "/shirts-category.jpg", productCount: 20, status: "Active" },
  { id: 5, name: "Footwear", image: "/footwear-category.jpg", productCount: 10, status: "Active" },
  { id: 6, name: "Accessories", image: "/accessories-category.jpg", productCount: 18, status: "Active" },
]

export const mockUsers = [
  {
    id: 1,
    name: "James Morrison",
    email: "james@example.com",
    role: "Customer",
    joinDate: "2024-01-15",
    orders: 5,
    status: "Active",
  },
  {
    id: 2,
    name: "Alexander Chen",
    email: "alexander@example.com",
    role: "Customer",
    joinDate: "2024-02-20",
    orders: 3,
    status: "Active",
  },
  {
    id: 3,
    name: "Thomas Blackwell",
    email: "thomas@example.com",
    role: "Admin",
    joinDate: "2024-03-10",
    orders: 8,
    status: "Active",
  },
  {
    id: 4,
    name: "Michael Sterling",
    email: "michael@example.com",
    role: "Customer",
    joinDate: "2024-01-05",
    orders: 2,
    status: "Inactive",
  },
  {
    id: 5,
    name: "David Harrison",
    email: "david@example.com",
    role: "Customer",
    joinDate: "2024-04-01",
    orders: 6,
    status: "Active",
  },
  {
    id: 6,
    name: "Robert Wilson",
    email: "robert@example.com",
    role: "Admin",
    joinDate: "2024-01-20",
    orders: 12,
    status: "Active",
  },
  {
    id: 7,
    name: "Christopher Hall",
    email: "christopher@example.com",
    role: "Customer",
    joinDate: "2024-03-15",
    orders: 4,
    status: "Active",
  },
  {
    id: 8,
    name: "Benjamin Scott",
    email: "benjamin@example.com",
    role: "Customer",
    joinDate: "2024-02-10",
    orders: 7,
    status: "Active",
  },
]

export const mockOrders = [
  { id: "ORD-001", customer: "James Morrison", date: "2024-04-15", total: 1850, status: "Delivered" },
  { id: "ORD-002", customer: "Alexander Chen", date: "2024-04-14", total: 520, status: "Shipped" },
  { id: "ORD-003", customer: "Thomas Blackwell", date: "2024-04-13", total: 2100, status: "Processing" },
  { id: "ORD-004", customer: "Michael Sterling", date: "2024-04-12", total: 680, status: "Delivered" },
  { id: "ORD-005", customer: "David Harrison", date: "2024-04-11", total: 1200, status: "Pending" },
  { id: "ORD-006", customer: "Robert Wilson", date: "2024-04-10", total: 950, status: "Shipped" },
  { id: "ORD-007", customer: "Christopher Hall", date: "2024-04-09", total: 1500, status: "Delivered" },
  { id: "ORD-008", customer: "Benjamin Scott", date: "2024-04-08", total: 750, status: "Processing" },
  { id: "ORD-009", customer: "James Morrison", date: "2024-04-07", total: 1100, status: "Delivered" },
  { id: "ORD-010", customer: "Alexander Chen", date: "2024-04-06", total: 2300, status: "Pending" },
]

export const dashboardStats = {
  totalRevenue: "$45,230",
  totalOrders: 1240,
  totalCustomers: 856,
  averageOrderValue: "$36.50",
}

export const mockVouchers = [
  {
    id: 1,
    code: "STYLE2024",
    description: "Premium collection discount",
    discount: 15,
    discountType: "percentage",
    minPurchase: 100,
    maxUses: 100,
    usedCount: 45,
    quantity: 100,
    expiryDate: "2024-12-31",
    status: "Active",
    hasExpiration: true,
  },
  {
    id: 2,
    code: "SPRING30",
    description: "Spring collection special",
    discount: 30,
    discountType: "fixed",
    minPurchase: 200,
    maxUses: 50,
    usedCount: 50,
    quantity: 0,
    expiryDate: "2024-05-31",
    status: "Inactive",
    hasExpiration: true,
  },
  {
    id: 3,
    code: "WELCOME10",
    description: "New customer welcome offer",
    discount: 10,
    discountType: "percentage",
    minPurchase: 50,
    maxUses: 200,
    usedCount: 120,
    quantity: 200,
    expiryDate: "No Expiration",
    status: "Active",
    hasExpiration: false,
  },
  {
    id: 4,
    code: "LUXURY50",
    description: "Luxury item discount",
    discount: 50,
    discountType: "fixed",
    minPurchase: 500,
    maxUses: 30,
    usedCount: 12,
    quantity: 30,
    expiryDate: "2024-08-31",
    status: "Active",
    hasExpiration: true,
  },
  {
    id: 5,
    code: "VIPEXC20",
    description: "VIP exclusive discount",
    discount: 20,
    discountType: "percentage",
    minPurchase: 300,
    maxUses: 25,
    usedCount: 8,
    quantity: 25,
    expiryDate: "2024-07-15",
    status: "Active",
    hasExpiration: true,
  },
  {
    id: 6,
    code: "SUMMERSALE15",
    description: "Summer sale discount",
    discount: 15,
    discountType: "percentage",
    minPurchase: 75,
    maxUses: 150,
    usedCount: 62,
    quantity: 150,
    expiryDate: "2024-09-30",
    status: "Active",
    hasExpiration: true,
  },
  {
    id: 7,
    code: "FLASH25",
    description: "Flash sale promotion",
    discount: 25,
    discountType: "fixed",
    minPurchase: 150,
    maxUses: 80,
    usedCount: 79,
    quantity: 1,
    expiryDate: "2024-05-20",
    status: "Active",
    hasExpiration: true,
  },
]
